tasks:
  - before: cd moveit-whats
    name: Yarn Window
    command: yarn && yarn install

  - openMode: split-right
  - openIn: right
    name: Project Terminal
    command: clear && echo "BEFORE > Add MONGODB_URI inside .env file!" && echo "TO RUN > yarn dev"
ports:
  - port: 3000
    onOpen: open-browser